#Design for Volvo Group

name: Deploy Node.js to Azure
on:
  push:
    branches: [ main ]

permissions:
  id-token: write # requiredï¼šOIDC id token
  contents: read

jobs:
  provision-and-deploy:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_USE_OIDC: true

    steps:
      - uses: actions/checkout@v4

      # login Azure using OIDC
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false # disable wrapper get stdout

      - name: Terraform Apply
        id: tf_apply
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve -var-file=prod.tfvars
          
          # make output to environment variable
          
          echo "ACR_SERVER=$(terraform output -raw acr_login_server)" >> $GITHUB_ENV
          echo "ACR_NAME=$(terraform output -raw acr_name)" >> $GITHUB_ENV
          echo "AKS_NAME=$(terraform output -raw aks_cluster_name)" >> $GITHUB_ENV
          echo "RG_NAME=$(terraform output -raw resource_group_name)" >> $GITHUB_ENV

      - name: Build Docker image and Push to ACR
        run: |
          az acr login --name ${{ env.ACR_NAME }}
          docker build -t ${{ env.ACR_SERVER }}/nodeapp:${{ github.sha }} .
          docker push ${{ env.ACR_SERVER }}/nodeapp:${{ github.sha }}

      - name: Set AKS Context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ env.RG_NAME }}
          cluster-name: ${{ env.AKS_NAME }}

      - name: Deploy to K8s
        run: |
          sed -i "s|IMAGE_PLACEHOLDER|${{ env.ACR_SERVER }}/nodeapp:${{ github.sha }}|g" k8s/deployment.yaml
          kubectl apply -f k8s/deployment.yaml

